import sys
from ast import literal_eval

def readFile( filename ):
  """ Used to open files generated by the HoughTransform code. It reads the x, y coordinates of
      the circle points into a list of list (points) and seperately into lists x and y

  :param str filename: file to be opened
  :returns dictionary with following keys: Points, x and y. Points contains

  """
  try:
    f = open( filename, 'r' )
  except Exception, e:
    sys.exit(e)
  center = []
  radius = []
  x = []
  y = []
  for line in f:
    if not line.startswith('#'):
        sep = line.split()
        x.append(float(sep[1]))
        y.append(float(sep[2]))
    if 'Center' in line:
      sep = line.split()
      tmp = literal_eval( sep[8] )
      center.append( tmp )

    if 'Radius' in line:
      sep = line.split()
      radius.append( float( sep[6] ) )

  return { 'x' : x, 'y' : y, 'Center' : center, 'Radius' : radius }
